# Generated by Django 4.1.5 on 2024-01-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(
                blank=True, default="images/default.jpg", null=True, upload_to="images"
            ),
        ),
    ]
