# Generated by Django 4.1.5 on 2024-01-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginauth", "0002_alter_profile_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(
                blank=True, default="media/default.jpg", null=True, upload_to="media"
            ),
        ),
    ]
